### ISSUE TITLE
Time and memory consumption

### ISSUE THREAD

**Issue by leishenggit** [BGI-shenzhen/VCF2Dis#2]
Is there any descriptions about time and memory cconsumption? It would be helpful when running the program in PBS ( Protable Batch System).

**Comment by hewm2008** [comment]
For  VCF  file . 
A     Memory 
The memory consumed is about 10M ，and there is almost no need to consider the cost of memory。

B   Speed 
The speed has been adjusted and optimized many times, and the version after 1.40 is very fast. The time is related to the amount of sample and the snp dataset. The more sites there are, the time increases in proportion. The more the sample amount, the more time increases. It takes about 1 day for 1000 samples of 1M sites.

**Comment by leishenggit** [comment]
Thanks for your explanation. But I got a new question as shown below

![1](https://user-images.githubusercontent.com/11373459/140277706-5f2803f9-1648-4c60-a9d0-9638aac55406.png)

The program is killed.  What causes it？

**Comment by hewm2008** [comment]
I know the reason.
too many  sample  :     2852900  , it  will need a initialize a two-dimensional matrix (2852900 * 2852900); so this will take a big Memory.        2852900 * 2852900   
I suggest using one sample for the same genotype.
