### ISSUE TITLE
how to get SNP tree with distance and bootstrap ？

### ISSUE THREAD

**Issue by mengxiaoqian** [BGI-shenzhen/VCF2Dis#3]
hi， 
   I use this methods "an Example of nj-tree with boostrap", but I just get a tree "Final_boostrap.tre" with bootstrap values in tree branch rather than in tree node finnally!  
[Final_boostrap_test.txt](https://github.com/BGI-shenzhen/VCF2Dis/files/9797136/Final_boostrap_test.txt)

**Comment by hewm2008** [comment]
1  经打开了你的文件，你的tree是没有问题的，是带有boostrap值的树
2  本程序是没办法即带有boostrap值和枝长的。      
3  VCF2dis的两个例子，例1 是展示带有枝长，  例2 如何构带有boostrap值的tree

1 After opening your file, your tree is no problem, it is a tree with boostrap value. 
2 There is no way for this program to have boostrap values ​​and branch lengths.
3 Two examples of VCF2dis, example 1 is to show with branch length, example 2 how to construct tree with boostrap value
